import os
import json
import ollama
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List, Optional
from dotenv import load_dotenv

load_dotenv()

from agent import check_and_run_tools, get_mcp_tools, get_system_prompt
from logger import log_info, log_error

app = FastAPI(title="GemmaJnana Gateway")

# Enable CORS for the frontend chat client
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MODEL_NAME = os.getenv("MODEL_NAME", "gemma4:e4b")

class Message(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: List[Message]
    temperature: float = 0.3
    session_name: str = "default_session"
    domain: str = "travel"

@app.get("/health")
def health_check():
    try:
        models = [m.model for m in ollama.list().models]
        if any(MODEL_NAME in name for name in models):
            return {"status": "healthy", "model": MODEL_NAME}
        return {"status": "warning", "warning": f"Model {MODEL_NAME} not loaded."}
    except Exception as e:
        return {"status": "unhealthy", "error": str(e)}

@app.get("/tools")
async def get_tools(domain: str = "travel"):
    try:
        tools = await get_mcp_tools(domain=domain)
        return tools
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/skills")
def get_skills(domain: str = "travel"):
    """
    Expose dynamic workflow skills based on domain.
    """
    skills_list = []
    skills_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mcp_servers", domain, "skills")
    if os.path.exists(skills_dir):
        try:
            for file in sorted(os.listdir(skills_dir)):
                if file.endswith(".json"):
                    with open(os.path.join(skills_dir, file), "r") as f:
                        skill_data = json.load(f)
                        skills_list.append(skill_data)
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
    return skills_list

@app.post("/chat")
async def chat_completion(request: ChatRequest):
    session = request.session_name
    domain = request.domain
    try:
        log_info(session, f"Received chat completion request for domain '{domain}'. Temperature={request.temperature}")
        messages_list = [msg.model_dump() for msg in request.messages]
        
        # Inject system prompt specific to domain
        sys_msg = {"role": "system", "content": get_system_prompt(domain)}
        if messages_list and messages_list[0].get("role") == "system":
            messages_list[0] = sys_msg
        else:
            messages_list.insert(0, sys_msg)
            
        log_info(session, f"Message history loaded with system prompt for domain '{domain}'. Total messages: {len(messages_list)}")
        
        tool_messages = []
        tool_results = {}
        tool_llm_calls = 0

        async for event in check_and_run_tools(messages_list, MODEL_NAME, domain, session):
            if event["type"] == "result":
                tool_messages = event["tool_messages"]
                tool_results = event["tool_results"]
                tool_llm_calls = event["llm_calls"]

        modified_messages = list(messages_list)
        if tool_messages:
            log_info(session, f"Extending history with {len(tool_messages)} tool message(s).")
            modified_messages.extend(tool_messages)

        log_info(session, "[LLM Call] Calling Ollama model for final response...")
        client = ollama.AsyncClient()
        response = await client.chat(
            model=MODEL_NAME,
            messages=modified_messages,
            options={"temperature": request.temperature}
        )
        log_info(session, "Response successfully generated by Ollama.")
        executed_tools = list(tool_results.keys())
        total_llm_calls = tool_llm_calls + 1
        log_info(session, f"Session Summary: Total LLM Calls: {total_llm_calls} | Executed Tool Calls: {executed_tools}")
        return response
    except Exception as e:
        log_error(session, f"Error in chat_completion: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    session = request.session_name
    domain = request.domain
    async def event_generator():
        try:
            log_info(session, f"Received chat stream request for domain '{domain}'. Temperature={request.temperature}")
            messages_list = [msg.model_dump() for msg in request.messages]
            
            # Inject system prompt specific to domain
            sys_msg = {"role": "system", "content": get_system_prompt(domain)}
            if messages_list and messages_list[0].get("role") == "system":
                messages_list[0] = sys_msg
            else:
                messages_list.insert(0, sys_msg)
                
            log_info(session, f"Message history loaded with system prompt for domain '{domain}'. Total messages: {len(messages_list)}")
            
            tool_messages = []
            tool_results = {}
            tool_llm_calls = 0

            async for event in check_and_run_tools(messages_list, MODEL_NAME, domain, session):
                if event["type"] == "result":
                    tool_messages = event["tool_messages"]
                    tool_results = event["tool_results"]
                    tool_llm_calls = event["llm_calls"]
                else:
                    # Stream tracer event directly to client UI
                    yield f"data: {json.dumps(event)}\n\n"

            modified_messages = list(messages_list)
            if tool_messages:
                log_info(session, f"Extending history with {len(tool_messages)} tool message(s).")
                modified_messages.extend(tool_messages)

            log_info(session, "[LLM Call] Calling Ollama chat stream...")
            client = ollama.AsyncClient()
            stream = await client.chat(
                model=MODEL_NAME,
                messages=modified_messages,
                stream=True,
                options={"temperature": request.temperature}
            )
            
            chunk_count = 0
            async for chunk in stream:
                content = chunk.message.content
                done = getattr(chunk, "done", False)
                chunk_count += 1
                yield f"data: {json.dumps({'content': content, 'done': done})}\n\n"
                
            log_info(session, f"Stream completed successfully. Sent {chunk_count} chunk(s).")
            executed_tools = list(tool_results.keys())
            total_llm_calls = tool_llm_calls + 1
            log_info(session, f"Session Summary: Total LLM Calls: {total_llm_calls} | Executed Tool Calls: {executed_tools}")
        except Exception as e:
            log_error(session, f"Error in chat_stream event_generator: {e}")
            yield f"data: {json.dumps({'error': str(e)})}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")

if __name__ == "__main__":
    import uvicorn
    host = os.getenv("GATEWAY_HOST", "127.0.0.1")
    port = int(os.getenv("GATEWAY_PORT", "8435"))
    uvicorn.run(app, host=host, port=port)
